version: '3.8'
services: 
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes: 
      - "./:/app"
    ports: 
      - "5000:5002"
    depends_on: 
      - mysql

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: klikvoting
      MYSQL_DATABASE: klikvoting
      MYSQL_ROOT_PASSWORD: klikvoting
